/*
 * Did Mapping MS
 * A microservice for storing associations between user IDs and DIDs for applications that want to use DID-Auth
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sphereon.sdk.did.mapping.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DidInfo
 */
@JsonPropertyOrder({
  DidInfo.JSON_PROPERTY_BOX_PUB,
  DidInfo.JSON_PROPERTY_PUSH_TOKEN,
  DidInfo.JSON_PROPERTY_DID
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-07T13:14:15.882187+01:00[Europe/Amsterdam]")
public class DidInfo {
  public static final String JSON_PROPERTY_BOX_PUB = "boxPub";
  private String boxPub;

  public static final String JSON_PROPERTY_PUSH_TOKEN = "pushToken";
  private String pushToken;

  public static final String JSON_PROPERTY_DID = "did";
  private String did;


  public DidInfo boxPub(String boxPub) {
    
    this.boxPub = boxPub;
    return this;
  }

   /**
   * Get boxPub
   * @return boxPub
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BOX_PUB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBoxPub() {
    return boxPub;
  }


  public void setBoxPub(String boxPub) {
    this.boxPub = boxPub;
  }


  public DidInfo pushToken(String pushToken) {
    
    this.pushToken = pushToken;
    return this;
  }

   /**
   * Get pushToken
   * @return pushToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PUSH_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPushToken() {
    return pushToken;
  }


  public void setPushToken(String pushToken) {
    this.pushToken = pushToken;
  }


  public DidInfo did(String did) {
    
    this.did = did;
    return this;
  }

   /**
   * Get did
   * @return did
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDid() {
    return did;
  }


  public void setDid(String did) {
    this.did = did;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DidInfo didInfo = (DidInfo) o;
    return Objects.equals(this.boxPub, didInfo.boxPub) &&
        Objects.equals(this.pushToken, didInfo.pushToken) &&
        Objects.equals(this.did, didInfo.did);
  }

  @Override
  public int hashCode() {
    return Objects.hash(boxPub, pushToken, did);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DidInfo {\n");
    sb.append("    boxPub: ").append(toIndentedString(boxPub)).append("\n");
    sb.append("    pushToken: ").append(toIndentedString(pushToken)).append("\n");
    sb.append("    did: ").append(toIndentedString(did)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

