/*
 * Did Mapping MS
 * A microservice for storing associations between user IDs and DIDs for applications that want to use DID-Auth
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sphereon.sdk.did.mapping.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sphereon.sdk.did.mapping.model.DidMap;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DidMappingRequest
 */
@JsonPropertyOrder({
  DidMappingRequest.JSON_PROPERTY_DID_MAPS
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-11T11:15:14.749995+01:00[Europe/Amsterdam]")
public class DidMappingRequest {
  public static final String JSON_PROPERTY_DID_MAPS = "didMaps";
  private List<DidMap> didMaps = null;


  public DidMappingRequest didMaps(List<DidMap> didMaps) {
    
    this.didMaps = didMaps;
    return this;
  }

  public DidMappingRequest addDidMapsItem(DidMap didMapsItem) {
    if (this.didMaps == null) {
      this.didMaps = new ArrayList<>();
    }
    this.didMaps.add(didMapsItem);
    return this;
  }

   /**
   * Get didMaps
   * @return didMaps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DID_MAPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DidMap> getDidMaps() {
    return didMaps;
  }


  public void setDidMaps(List<DidMap> didMaps) {
    this.didMaps = didMaps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DidMappingRequest didMappingRequest = (DidMappingRequest) o;
    return Objects.equals(this.didMaps, didMappingRequest.didMaps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(didMaps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DidMappingRequest {\n");
    sb.append("    didMaps: ").append(toIndentedString(didMaps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

