/*
 * Did Mapping MS
 * A microservice for storing associations between user IDs and DIDs for applications that want to use DID-Auth
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sphereon.sdk.did.mapping.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DidInfo
 */
public class DidInfoTest {
    private final DidInfo model = new DidInfo();

    /**
     * Model tests for DidInfo
     */
    @Test
    public void testDidInfo() {
        // TODO: test DidInfo
    }

    /**
     * Test the property 'boxPub'
     */
    @Test
    public void boxPubTest() {
        // TODO: test boxPub
    }

    /**
     * Test the property 'pushToken'
     */
    @Test
    public void pushTokenTest() {
        // TODO: test pushToken
    }

    /**
     * Test the property 'did'
     */
    @Test
    public void didTest() {
        // TODO: test did
    }

}
