/*
 * Did Mapping MS
 * A microservice for storing associations between user IDs and DIDs for applications that want to use DID-Auth
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sphereon.sdk.did.mapping.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sphereon.sdk.did.mapping.model.DidMap;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DidMappingResponse
 */
public class DidMappingResponseTest {
    private final DidMappingResponse model = new DidMappingResponse();

    /**
     * Model tests for DidMappingResponse
     */
    @Test
    public void testDidMappingResponse() {
        // TODO: test DidMappingResponse
    }

    /**
     * Test the property 'didMaps'
     */
    @Test
    public void didMapsTest() {
        // TODO: test didMaps
    }

}
